### PR TITLE
Service Delivery trigger and handler framework, FeatureGate custom metadata, BucketedField custom metadata

### PR DESCRIPTION
**Pull request by bethbrains**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] ~~Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage~~
- [ ] ~~CRUD/FLS is enforced in Apex~~
- [ ] ~~Permission sets are updated to account for CRUD|FLS|Tab|Classes~~
- [ ] ~~Field sets are updated to account for new fields~~
- [ ] ~~UX approval or UX not necessary~~
- [x] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [x] All **acceptance criteria** have been met
    - [x] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] ~~PR contains draft release notes~~
- [ ] QE story level testing completed

### CODE REVIEW

**Comment by bethbrains** [comment]
[W-8595696](https://gus.lightning.force.com/a07B0000008lmEMIAY)

**Review by jjbennett — APPROVED** [review]

**Comment by jjbennett** [comment]
@AndersonTarren @bmuniswamy  - This looks good to me but I paired with Beth, would you two mind taking another peak at it and let us know if you have any concerns. I do not believe we can actually QE this since this is all just setup and does not actually do anything yet.

**Review by bmuniswamy — APPROVED** [review]
This looks good to me @jjbennett !! I have one small nit picky comment but other than it looks good. @AndersonTarren , can you please glance over this.

**Review by AndersonTarren — APPROVED** [review]
**Great work!**  This is a good start.  We have a lot to research yet in terms of approach, but this gives us the foundation we need to get going.

**Pull request merged**
