### PR TITLE
PMM MetaDeploy may-12-2020 Translation Update

### PR DESCRIPTION
**Pull request by mikofang**
@AndersonTarren  PMM MetaDeploy translation update has been delivered.

Please help to create screenshots for LQA verification. Thanks!

cc: @eliseforce

### CODE REVIEW

**Comment by AndersonTarren** [comment]
@davidmreed  is there an easy way to get screenshots for @mikofang for verification here?

**Comment by davidmreed** [comment]
Yes, I will generate screenshots.

**Comment by mikofang** [comment]
@AndersonTarren I have pushed the commit 3fde97b for DNT product names.  Looks like there were changes to the l10n files and there are conflicts that need to be resolved.

cc: @eliseforce

**Comment by davidmreed** [comment]
I fixed the merge conflicts, but there is an issue with the legal terms, which is (one of) the manual changes I had to make to the translation files. We inserted them in English, but these files revert to the original placeholders.

That's easy to fix, but I'm wondering whether it makes more sense to pause until we get the final translated legal terms from SFDO Legal to integrate everything. I understand we should get them this week. (cc @meggraySFDO).

**Comment by mikofang** [comment]
@davidmreed Just to follow up. Do you typically manually insert legal text from legal translators to the metadeploy json file? The process would cause conflict with l10n process, so I would like to understand it. Thanks!

cc: @dmkud

**Comment by davidmreed** [comment]
@mikofang @meggraySFDO @AndersonTarren I've added LQA screenshots in Google Drive here: https://drive.google.com/open?id=1F_ef3QjpilL-a58Oz5meLwwnnLdtT2WD

This includes merging in changes from SFDO Legal, resolving merge conflicts, and adding in missing links that were updated after the original translation pass.

Please note that the postinstall message is shown in English in all screenshots. This is an issue in MetaDeploy that our team is working to correct soon.

**Comment by mikofang** [comment]
Thanks @davidmreed !

Please provide repo access for Dmitry (dmkud), since he will be the LPM for PMM and CaseMan. Thanks!

FYI, @eliseforce

**Comment by davidmreed** [comment]
@dmkud  Just want to make sure this one is on the radar.

**Comment by dmkud** [comment]
> @dmkud Just want to make sure this one is on the radar.

Yes, it is. I requested an update from our partner on where they are

**Pull request merged**
