### PR TITLE
Always show BSDT footer, styled BSDT modal

### PR DESCRIPTION
**Pull request by bethbrains**
# Critical Changes

# Changes
- When viewed from CaseMan, "Manage Services" will now show the same footer as BSDT. The "Done" button will close the Manage Services modal.

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))
- [ ] Base axe-core JEST test included for any new LWC (No critical violations)
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets & field sets are updated to account for CRUD/FLS/TABS for new object metadata
- [ ] All modified classes are unit tested (Apex) at 100% coverage
- [ ] UX approval or UX not necessary
- [ ] PR contains draft release notes
- [ ] Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] QE story level testing completed

### CODE REVIEW

**Comment by bethbrains** [comment]
[W-7843922](https://gus.lightning.force.com/a07B0000008WMJCIA4)

**Comment by bethbrains** [comment]
**To test,** add `default-visible="true"` to `c-modal` in `serviceDeliveryModal.html`, then add `<targets><target>lightning__HomePage</target></targets>` to `serviceDeliveryModal.html.js-meta.xml` and then drag the component onto the app home page.

**Comment by bethbrains** [comment]
@AndersonTarren - this is currently pointed at master. please adjust if necessary.

**Review by jjbennett — APPROVED** [review]
Looks great, discussed with Tarren and we are ok with having to scroll down to the footer if they add a bunch of rows, the assumption is that the majority of users will prolly be adding just one at a time.

**Comment by jjbennett** [comment]
[W-8125688](https://gus.lightning.force.com/a07B00000089hgOIAQ)

**Comment by bethbrains** [comment]
@jjbennett fixed! larger spacing when in the modal, tighter when in the bsdt tab. Take a look and release to QE if you're happy. Thanks!

**Pull request merged**
