### PR TITLE
Mass create PE's from contact list views

### PR DESCRIPTION
**Pull request by bmuniswamy**
This PR only affects internal dev/testing. Added the 'Add Contact To Program' quick action to the List View Layout under Search Layouts for Salesforce Classic option. This is in the unpackaged/dev folder so when we create a new dev org we should be able to see the quick action button on Contact list views.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
~~- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage~~  
~~- [ ] CRUD/FLS is enforced in Apex~~
~~- [ ] Permission sets are updated to account for CRUD|FLS|Tab|Classes~~
~~- [ ] Field sets are updated to account for new fields~~
~~- [ ] UX approval or UX not necessary~~
- [x] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [x] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [x] PR contains draft release notes
- [ ] QE story level testing completed

### CODE REVIEW

**Comment by bmuniswamy** [comment]
[W-8292289](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AWmfIAG/view)

**Comment by jjbennett** [comment]
@bmuniswamy this isn't working for me, I didn't have a chance to dive into it but if you get in before me maybe you can check it out. I ran dev_org but I don't have that button on my list views.

**Comment by bmuniswamy** [comment]
@jjbennett , Can we meet after you are in. I just ran the dev_org flow and I am seeing the button

**Review by jjbennett — APPROVED** [review]
So weird, not sure what happened when I first checked out your branch but I'm glad you saw it too so you know I wasn't totally losing it lol. It works! Really great work figuring out all the edges on this one!

**Pull request merged**
