### PR TITLE
Seed group BSDT rows with selected participants and defaults

### PR DESCRIPTION
**Pull request by bethbrains**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets are updated to account for CRUD|FLS|Tab|Classes
- [ ] Field sets are updated to account for new fields
- [ ] UX approval or UX not necessary
- [ ] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] PR contains draft release notes
- [ ] QE story level testing completed

### CODE REVIEW

**Comment by bethbrains** [comment]
[W-8922222](https://gus.lightning.force.com/lightning/_classic/%2Fa07B00000097DnWIAU)

**Review by AndersonTarren — CHANGES_REQUESTED** [review]
Seeing an issue when loading participants

bsdt-bulk-row-issue

**Comment by AndersonTarren** [comment]
Tried again and saw a different issue, where the first row was correct - but locked.  All other rows were incorrect.

bsdt-seeding-issue

**Comment by bmuniswamy** [comment]
I don't think this is an issue with this work item but I found that when a record is saved and the delete button is clicked, the confirmation modal shows up and once delete it clicked the modal is not dismissed. I am able to see the toast saying the record was deleted but the confirmation modal does not close. Screen shot attached:

image

**Comment by AndersonTarren** [comment]
One more issue 
bsdt-empty-row-save

**Review by AndersonTarren — APPROVED** [review]

**Pull request merged**
