### PR TITLE
BSDT Modal Not Resetting Properly

### PR DESCRIPTION
**Pull request by AndersonTarren**
# Critical Changes

# Changes
Fixes resetUI method not properly eliminating the first existing row.

# Issues Closed
[W-11003158](https://gus.lightning.force.com/a07EE00000v1CwPYAU)

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets are updated to account for CRUD|FLS|Tab|Classes
- [ ] Field sets are updated to account for new fields
- [ ] UX approval or UX not necessary
- [ ] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] PR contains draft release notes
- [ ] QE story level testing completed

### CODE REVIEW

**Comment by AndersonTarren** [comment]
@jjbennett The issue with the BSDT modal not being reset appears to be with the resetUI method.  To test this, I added a button directly to the BSDT UI that calls resetUI.  With the first row populated, as expected, it didn't clear.

I tried a variety of tricks, cloning the array, etc.  The only thing that worked in all situations was a small delay in adding a new row.  Some of my earlier attempts worked fine with just 1 populated row, but if you add multiple populated rows - those solutions fell apart.

I don't love the delay solution, curious if you have a better solution.

**Comment by jjbennett** [comment]
My thought was we could reset the defaultsValues to an empty object?

**Comment by AndersonTarren** [comment]
Mine as well :). But it appears we're already doing that.  If you console.log the value in CaseMan you should see that we're indeed passing an empty object.

**Comment by bmuniswamy** [comment]
@jjbennett, I commented out the timeout code in resetUI and set the private defaultValues to an empty object. Now the behavior is that the first time the modal loads after the PE is cleared , PE still shows up but then subsequent loads the PE value is blank in the modal. Can you please look at it and then maybe we can set this to blank instead of using the timeout.

**Comment by jjbennett** [comment]
Renaming branch and creating a new [240 PR.](https://github.com/SalesforceFoundation/PMM/pull/616)

**Pull request closed without merging**
